### ISSUE TITLE
proposal framework for api nodes documentation

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#650]
i am working on a draft to add to the wiki as i think we have no document to cover specifically the api node configuration:

https://github.com/oxarbitrage/worker-proposals/blob/master/bitshares_api_node.md

it is just a draft at the moment.

This will include https://github.com/bitshares/bitshares-core/issues/624 and https://github.com/bitshares/bitshares-core/issues/550

I will go ahead and get the commands for everything in there if you give me the ok to continue with it. Need help with securing the connection part as i never made it myself!

**Comment by xeroc** [comment]
docker-compose.yaml:
```
version: '3'
services:

 fullnode:
  # Image to run
  image: fb3d7a273ce4
  # Optional environmental variables
  # environment:
  ports:
   - "0.0.0.0:8090:8090"
  volumes:
  - "bitshares-fullnode:/var/lib/bitshares"

 delayed_node:
  # Image to run
  image: fb3d7a273ce4
  # Optional environmental variables
  environment:
   - 'BITSHARESD_PLUGINS=delayed_node witness'
   - 'BITSHARESD_TRUSTED_NODE=ws://fullnode:8090'
  ports:
   - "0.0.0.0:8091:8090"
  volumes:
  - "bitshares-fullnode:/var/lib/bitshares"
    #  links: 
    #- fullnode

volumes:
 bitshares-fullnode:
```

then

`docker-compose up`
